flags:
  time-locale-compat:
    old-locale: false
packages:
- '.'
extra-deps:
- RSA-2.2.0
- SHA-1.6.4.2
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-0.9.0.1
- aeson-compat-0.3.3.0
- aeson-pretty-0.7.2
- ansi-terminal-0.6.2.3
- appar-0.1.4
- asn1-encoding-0.9.3
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.0
- attoparsec-0.13.0.2
- authenticate-oauth-1.5.1.2
- auto-update-0.1.4
- base-compat-0.9.1
- base-orphans-0.5.4
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- bifunctors-5.3
- blaze-builder-0.4.0.2
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- case-insensitive-1.2.0.6
- cereal-0.5.2.0
- cmdargs-0.10.14
- comonad-5
- conduit-1.2.6.6
- conduit-extra-1.1.13.1
- connection-0.2.5
- contravariant-1.4
- cookie-0.4.2
- crypto-api-0.13.2
- crypto-pubkey-types-0.4.3
- cryptohash-0.11.9
- cryptonite-0.16
- data-default-0.7.0
- data-default-class-0.1.0
- data-default-instances-base-0.1.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- distributive-0.5.0.2
- dlist-0.7.1.2
- easy-file-0.2.1
- entropy-0.3.7
- esqueleto-2.4.2
- exceptions-0.8.2.1
- expiring-cache-map-0.0.5.4
- fail-4.9.0.0
- fast-logger-2.4.6
- free-4.12.4
- hashable-1.2.4.0
- hex-0.1.2
- hourglass-0.2.10
- http-api-data-0.2.2
- http-client-0.4.28
- http-client-tls-0.2.4
- http-conduit-2.1.10.1
- http-date-0.0.6.1
- http-types-0.9
- http2-1.6.0
- iproute-1.7.0
- kan-extensions-5.0.1
- lens-4.14
- lens-aeson-1.0.0.5
- lifted-base-0.2.3.6
- memory-0.13
- mime-types-0.1.0.7
- mmorph-1.0.6
- monad-control-1.0.1.0
- monad-logger-0.3.18
- monad-loops-0.4.3
- mtl-2.2.1
- nats-1.1
- network-2.6.2.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parallel-3.2.1.0
- parsec-3.1.11
- path-pieces-0.2.1
- pem-0.2.2
- persistent-2.2.4.1
- persistent-postgresql-2.2.2
- persistent-template-2.1.8.1
- postgresql-libpq-0.9.1.1
- postgresql-simple-0.5.2.0
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- psqueues-0.2.2.1
- pureMD5-2.1.3
- random-1.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resource-pool-0.2.3.2
- resourcet-1.1.7.4
- scientific-0.3.4.6
- scotty-0.11.0
- semigroupoids-5.0.1
- semigroups-0.18.1
- silently-1.2.5
- simple-sendfile-0.2.24
- socks-0.5.5
- stm-2.4.4.1
- stm-chans-3.0.0.4
- streaming-commons-0.1.15.5
- stringsearch-0.3.6.6
- syb-0.6
- tagged-0.8.4
- text-1.2.2.1
- time-locale-compat-0.1.1.1
- tls-1.3.8
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.2.0
- unix-time-0.3.6
- unordered-containers-0.2.7.0
- uuid-types-1.0.3
- vault-0.3.0.6
- vector-0.11.0.0
- void-0.7.1
- wai-3.2.1.1
- wai-extra-3.0.15.1
- wai-logger-2.2.7
- wai-middleware-static-0.8.0
- warp-3.2.6
- word8-0.1.2
- wreq-0.4.1.0
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.3
- x509-validation-1.6.3
- zlib-0.6.1.1
resolver: ghc-7.10
